-- =====================================================
-- PROFESSIONS — "Sua profissão está em risco?" hub + quiz
--
-- Product goal: a non-tech visitor picks their profession (or answers
-- the quiz) and sees an AI-exposure verdict for it — how much of the
-- day-to-day is likely to be augmented vs. automated by generative AI
-- in Brazil over the next 3-5 years — backed by real job postings and
-- news, not a generic take.
--
-- Architecture mirrors 010_niches.sql: one embedding per profession
-- (computed once from name+descriptor), ANN search against the
-- existing news.embedding / vagas_ia.embedding columns via <=>
-- (cosine distance). The exposure verdict itself (exposure_score,
-- summary, tasks_augmented/at_risk, bridge_skills) is generated by the
-- build-profession-index edge function (gpt-4o-mini, JSON mode) from
-- that evidence, and always lands in status='review' — a human must
-- flip it to 'published' in Studio. This migration only creates the
-- schema and seeds the descriptive columns (name/cluster/descriptor),
-- never the generated fields.
-- =====================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- =====================================================
-- 1. professions — table
-- =====================================================

CREATE TABLE IF NOT EXISTS professions (
  slug text PRIMARY KEY,
  name text NOT NULL,
  cluster text NOT NULL,
  descriptor text NOT NULL,
  exposure_score int,
  exposure_band text,
  summary text,
  tasks_augmented jsonb,
  tasks_at_risk jsonb,
  bridge_skills jsonb,
  evidence_job_ids text[],
  evidence_news_ids uuid[],
  embedding vector(1536),
  status text NOT NULL DEFAULT 'draft',
  generated_at timestamptz,
  model text,
  reviewed_at timestamptz,
  sort_order int NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Constraints added separately (can't IF NOT EXISTS a CHECK constraint directly)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'professions_cluster_check'
  ) THEN
    ALTER TABLE professions
      ADD CONSTRAINT professions_cluster_check
      CHECK (cluster IN ('negocios','saude','educacao','juridico','financas','marketing','tecnologia','criativo','operacoes','servicos'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'professions_exposure_score_check'
  ) THEN
    ALTER TABLE professions
      ADD CONSTRAINT professions_exposure_score_check
      CHECK (exposure_score IS NULL OR (exposure_score >= 0 AND exposure_score <= 100));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'professions_exposure_band_check'
  ) THEN
    ALTER TABLE professions
      ADD CONSTRAINT professions_exposure_band_check
      CHECK (exposure_band IS NULL OR exposure_band IN ('baixa','media','alta'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'professions_status_check'
  ) THEN
    ALTER TABLE professions
      ADD CONSTRAINT professions_status_check
      CHECK (status IN ('draft','review','published','rejected'));
  END IF;
END $$;

COMMENT ON COLUMN professions.descriptor IS
  '2-3 factual sentences (PT-BR) describing what the profession does day to day. Seed input for the embedding ("{name}. {descriptor}") and for the LLM exposure evaluation — never shown verbatim to end users (excluded from professions_public).';
COMMENT ON COLUMN professions.summary IS
  '3-5 sentence PT-BR verdict written by build-profession-index using non-deterministic language ("tende a", "parte das tarefas") — never a flat percentage claim.';
COMMENT ON COLUMN professions.evidence_job_ids IS
  'vagas_ia.job_id values used as evidence for the exposure verdict (up to 15). Required non-empty before build-profession-index will persist a verdict — see docs/PROFESSIONS.md governance rules.';
COMMENT ON COLUMN professions.embedding IS
  'text-embedding-3-small (1536d) over "{name}. {descriptor}". Populated by build-profession-index (service-role client) — never computed client-side. NULL until first generated; profession_jobs/profession_news return an empty set for a profession whose embedding is still NULL.';
COMMENT ON COLUMN professions.status IS
  'draft: seeded, not yet evaluated. review: LLM verdict generated, awaiting human review. published: live on the public site. rejected: reviewed and discarded (bad evidence/verdict) — kept for audit, never published.';

CREATE INDEX IF NOT EXISTS idx_professions_embedding_hnsw
  ON professions USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_professions_status ON professions (status);

-- =====================================================
-- 2. RLS — table locked down entirely for public roles, same rationale
-- as niches: exposes embedding/descriptor otherwise (RLS is row-level,
-- not column-level). professions_public is the only public surface.
-- =====================================================

ALTER TABLE professions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON professions FROM anon, authenticated;

DROP POLICY IF EXISTS "Block direct select on professions" ON professions;
CREATE POLICY "Block direct select on professions"
ON professions FOR SELECT
TO anon, authenticated
USING (false);

DROP POLICY IF EXISTS "Block direct writes on professions" ON professions;
CREATE POLICY "Block direct writes on professions"
ON professions FOR ALL
TO anon, authenticated
USING (false)
WITH CHECK (false);

-- =====================================================
-- 3. professions_public — view without embedding/descriptor,
-- published only. sort_order first, then name, mirrors niches_public
-- ordering conventions used by the frontend hub index.
-- =====================================================

CREATE OR REPLACE VIEW professions_public AS
SELECT
  slug, name, cluster,
  exposure_score, exposure_band, summary,
  tasks_augmented, tasks_at_risk, bridge_skills,
  status, reviewed_at, sort_order, updated_at
FROM professions
WHERE status = 'published';

GRANT SELECT ON professions_public TO anon, authenticated;

-- =====================================================
-- 4. Seed — 40 professions across the 10 clusters.
--
-- ON CONFLICT updates only the descriptive columns (name, cluster,
-- descriptor, sort_order) — generated fields (exposure_*, summary,
-- tasks_*, bridge_skills, evidence_*, embedding) and status are
-- deliberately left out of the UPDATE SET so re-running this
-- migration (e.g. after editing copy) never wipes an already-reviewed
-- profession. Re-run build-profession-index with { force: true,
-- slugs: [...] } after changing a descriptor.
-- =====================================================

INSERT INTO professions (slug, name, cluster, descriptor, sort_order) VALUES
('contador', 'Contador', 'financas', 'Escritura e concilia registros contábeis, apura impostos e prepara demonstrações financeiras para empresas ou clientes. Garante conformidade fiscal e tributária conforme a legislação vigente.', 1),
('advogado', 'Advogado', 'juridico', 'Presta consultoria jurídica, redige contratos e petições, e representa clientes em processos administrativos ou judiciais. Interpreta legislação e jurisprudência para embasar pareceres e estratégias.', 2),
('professor-ensino-medio', 'Professor de Ensino Médio', 'educacao', 'Planeja e ministra aulas para turmas do ensino médio, elabora avaliações e acompanha o desempenho pedagógico dos alunos. Adapta conteúdo e didática conforme a disciplina e o perfil da turma.', 3),
('medico-clinico', 'Médico Clínico', 'saude', 'Realiza consultas, diagnostica condições de saúde e prescreve tratamentos com base em exame clínico e histórico do paciente. Encaminha casos para especialistas e acompanha a evolução do tratamento.', 4),
('enfermeiro', 'Enfermeiro', 'saude', 'Presta cuidados diretos a pacientes, administra medicações e monitora sinais vitais em hospitais, clínicas ou UBS. Coordena equipes de técnicos de enfermagem e registra evolução clínica.', 5),
('farmaceutico', 'Farmacêutico', 'saude', 'Orienta sobre uso correto de medicamentos, avalia interações medicamentosas e supervisiona a dispensação em farmácias ou hospitais. Também atua em controle de qualidade e manipulação de fórmulas.', 6),
('psicologo', 'Psicólogo', 'saude', 'Conduz sessões terapêuticas, aplica testes psicológicos e elabora laudos e pareceres. Atua em clínicas, escolas ou empresas conforme a especialização (clínica, escolar, organizacional).', 7),
('analista-marketing', 'Analista de Marketing', 'marketing', 'Planeja e executa campanhas de marketing, analisa métricas de performance e ajusta estratégias de posicionamento de marca. Coordena ações entre mídia paga, conteúdo e branding.', 8),
('social-media', 'Social Media', 'marketing', 'Cria e programa conteúdo para redes sociais, interage com a audiência e monitora métricas de engajamento. Alinha calendário editorial com campanhas de marketing e identidade da marca.', 9),
('designer-grafico', 'Designer Gráfico', 'criativo', 'Cria peças visuais para campanhas, materiais impressos e digitais, aplicando identidade de marca e princípios de composição. Trabalha com ferramentas de edição de imagem e diagramação.', 10),
('redator-copywriter', 'Redator/Copywriter', 'criativo', 'Escreve textos publicitários, institucionais e de conteúdo para diferentes canais, adaptando tom e linguagem ao público-alvo. Revisa e otimiza textos para clareza e persuasão.', 11),
('jornalista', 'Jornalista', 'criativo', 'Apura, redige e edita matérias jornalísticas para veículos impressos, digitais ou audiovisuais. Verifica fontes, contextualiza fatos e cumpre prazos editoriais.', 12),
('analista-financeiro', 'Analista Financeiro', 'financas', 'Analisa demonstrações financeiras, projeta cenários e elabora relatórios para apoiar decisões de investimento ou orçamento. Acompanha indicadores de mercado e desempenho da empresa.', 13),
('bancario', 'Bancário', 'financas', 'Atende clientes em agências ou canais digitais, oferece produtos financeiros e processa operações bancárias. Segue normas de compliance e conhece o perfil de risco do cliente.', 14),
('corretor-imoveis', 'Corretor de Imóveis', 'servicos', 'Intermedeia negociações de compra, venda e locação de imóveis, apresenta propriedades e orienta clientes sobre documentação e financiamento. Prospecta clientes e mantém carteira de imóveis atualizada.', 15),
('vendedor', 'Vendedor', 'servicos', 'Apresenta produtos ou serviços, negocia condições comerciais e fecha vendas em loja física, online ou por telefone. Acompanha metas e mantém relacionamento pós-venda com clientes.', 16),
('atendente-sac', 'Atendente de SAC', 'servicos', 'Atende chamados de clientes por telefone, chat ou e-mail, resolve dúvidas e registra reclamações seguindo scripts e políticas da empresa. Encaminha casos complexos para níveis de suporte superiores.', 17),
('recepcionista', 'Recepcionista', 'servicos', 'Recebe e direciona visitantes, agenda compromissos e atende ligações em empresas, clínicas ou hotéis. Organiza a rotina da recepção e presta informações gerais ao público.', 18),
('assistente-administrativo', 'Assistente Administrativo', 'operacoes', 'Organiza documentos, agenda reuniões e apoia rotinas administrativas de um setor ou empresa. Elabora planilhas, relatórios simples e controla arquivos físicos e digitais.', 19),
('analista-rh', 'Analista de RH', 'negocios', 'Conduz processos de recrutamento, administra folha e benefícios, e apoia políticas de gestão de pessoas. Acompanha indicadores de clima organizacional e rotatividade.', 20),
('recrutador', 'Recrutador', 'negocios', 'Divulga vagas, triagem currículos e conduz entrevistas para identificar candidatos alinhados ao perfil da posição. Negocia proposta e acompanha o processo até a contratação.', 21),
('gerente-projetos', 'Gerente de Projetos', 'negocios', 'Planeja cronogramas, aloca recursos e acompanha entregas de projetos até sua conclusão. Gerencia riscos, orçamento e comunicação entre stakeholders e equipe.', 22),
('analista-dados', 'Analista de Dados', 'tecnologia', 'Coleta, trata e analisa dados para gerar relatórios e insights que apoiam decisões de negócio. Constrói dashboards e realiza análises estatísticas descritivas.', 23),
('desenvolvedor-software', 'Desenvolvedor de Software', 'tecnologia', 'Projeta, escreve e testa código para construir ou manter sistemas e aplicações. Participa de revisões de código e colabora com times de produto e design.', 24),
('suporte-ti', 'Suporte de TI', 'tecnologia', 'Resolve problemas técnicos de hardware, software e rede reportados por usuários internos ou clientes. Documenta chamados e escala incidentes complexos para times especializados.', 25),
('engenheiro-civil', 'Engenheiro Civil', 'operacoes', 'Planeja, projeta e acompanha a execução de obras, garantindo conformidade técnica e normas de segurança. Elabora orçamentos e cronogramas de construção.', 26),
('arquiteto', 'Arquiteto', 'criativo', 'Desenvolve projetos arquitetônicos residenciais e comerciais, equilibrando estética, funcionalidade e normas urbanísticas. Acompanha a obra e ajusta o projeto conforme necessário.', 27),
('tradutor', 'Tradutor', 'servicos', 'Traduz textos entre idiomas preservando sentido, tom e terminologia técnica do material original. Revisa traduções para precisão gramatical e cultural.', 28),
('fotografo', 'Fotógrafo', 'criativo', 'Planeja e realiza sessões fotográficas para eventos, produtos ou retratos, cuidando de composição, luz e edição das imagens. Entrega material tratado conforme o uso pretendido pelo cliente.', 29),
('produtor-video', 'Produtor de Vídeo', 'criativo', 'Planeja, grava e edita conteúdo em vídeo para campanhas, redes sociais ou produções institucionais. Coordena roteiro, captação e pós-produção conforme o objetivo da peça.', 30),
('nutricionista', 'Nutricionista', 'saude', 'Avalia hábitos alimentares e elabora planos nutricionais personalizados para pacientes ou clientes. Acompanha evolução e ajusta prescrições conforme objetivos de saúde.', 31),
('fisioterapeuta', 'Fisioterapeuta', 'saude', 'Avalia limitações funcionais e conduz sessões de reabilitação física usando técnicas manuais e equipamentos terapêuticos. Elabora planos de tratamento e acompanha a evolução motora do paciente.', 32),
('dentista', 'Dentista', 'saude', 'Realiza diagnóstico, tratamento e prevenção de problemas bucais, incluindo procedimentos restauradores e cirúrgicos. Orienta pacientes sobre higiene e saúde bucal.', 33),
('motorista-aplicativo', 'Motorista de Aplicativo', 'servicos', 'Transporta passageiros ou realiza entregas via plataformas digitais, seguindo rotas otimizadas pelo aplicativo. Gerencia própria agenda e mantém o veículo em condições adequadas.', 34),
('analista-logistica', 'Analista de Logística/Supply', 'operacoes', 'Planeja fluxos de estoque, transporte e distribuição para garantir entrega eficiente de produtos. Monitora indicadores de desempenho da cadeia de suprimentos.', 35),
('comprador', 'Comprador', 'operacoes', 'Negocia com fornecedores, avalia cotações e formaliza pedidos de compra de insumos ou produtos para a empresa. Monitora prazos de entrega e qualidade do fornecimento.', 36),
('auditor', 'Auditor', 'financas', 'Examina registros contábeis e processos internos para verificar conformidade com normas legais e políticas da empresa. Elabora relatórios apontando riscos e recomendações de controle.', 37),
('consultor-negocios', 'Consultor de Negócios', 'negocios', 'Analisa processos e desempenho de empresas clientes, propondo recomendações estratégicas e operacionais. Conduz diagnósticos e acompanha a implementação de melhorias.', 38),
('administrador-empresas', 'Administrador de Empresas', 'negocios', 'Planeja e coordena recursos financeiros, humanos e operacionais para atingir objetivos organizacionais. Toma decisões estratégicas com base em indicadores de desempenho.', 39),
('secretario-executivo', 'Secretário Executivo', 'operacoes', 'Organiza agenda, viagens e correspondências de executivos, além de preparar reuniões e documentos confidenciais. Atua como ponto de contato entre a liderança e demais áreas da empresa.', 40)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cluster = EXCLUDED.cluster,
  descriptor = EXCLUDED.descriptor,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- =====================================================
-- 5. Internal ANN helpers — NOT granted to anon.
--
-- pgvector ordering (`ORDER BY embedding <=> query_embedding`) isn't
-- expressible via PostgREST filters, so build-profession-index (which
-- runs under the service role, but still talks to Postgres only via
-- PostgREST/RPC through supabase-js) needs these as SECURITY DEFINER
-- RPCs. They are intentionally not part of the public contract: no
-- GRANT to anon/authenticated, only to service_role (implicit — RLS
-- and grants don't apply to the role used by the service key, but we
-- REVOKE FROM PUBLIC defensively and never GRANT to anon/authenticated
-- so a leaked anon key can't call them to enumerate arbitrary
-- job/news rows by an attacker-supplied embedding).
-- =====================================================

CREATE OR REPLACE FUNCTION _match_jobs_for_embedding(
  query_embedding vector(1536),
  match_count int DEFAULT 15
)
RETURNS TABLE (job_id text)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT v.job_id
  FROM vagas_ia v
  WHERE v.status = 'active'
    AND v.embedding IS NOT NULL
  ORDER BY v.embedding <=> query_embedding
  LIMIT LEAST(GREATEST(COALESCE(match_count, 15), 1), 50);
$$;

REVOKE ALL ON FUNCTION _match_jobs_for_embedding(vector, int) FROM PUBLIC;

CREATE OR REPLACE FUNCTION _match_news_for_embedding(
  query_embedding vector(1536),
  match_count int DEFAULT 8
)
RETURNS TABLE (news_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT n.id
  FROM news n
  WHERE (n.status = 'published' OR n.status IS NULL)
    AND n.embedding IS NOT NULL
  ORDER BY n.embedding <=> query_embedding
  LIMIT LEAST(GREATEST(COALESCE(match_count, 8), 1), 50);
$$;

REVOKE ALL ON FUNCTION _match_news_for_embedding(vector, int) FROM PUBLIC;

-- =====================================================
-- 6. RPC profession_jobs — active jobs by cosine to profession
-- embedding, published professions only.
-- =====================================================

CREATE OR REPLACE FUNCTION profession_jobs(
  profession_slug text,
  match_count int DEFAULT 12
)
RETURNS TABLE (
  id uuid,
  job_id text,
  job_title text,
  company_name text,
  job_url text,
  logo_url text,
  location text,
  is_remote boolean,
  seniority_level text,
  posted_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT v.id, v.job_id, v.job_title, v.company_name, v.job_url, v.logo_url, v.location, v.is_remote, v.seniority_level, v.posted_at
  FROM vagas_ia v
  JOIN professions p ON p.slug = profession_slug
  WHERE p.status = 'published'
    AND p.embedding IS NOT NULL
    AND v.embedding IS NOT NULL
    AND v.status = 'active'
  ORDER BY v.embedding <=> p.embedding
  -- Clamp: anon can call this RPC directly via PostgREST; never allow a bulk dump
  LIMIT LEAST(GREATEST(COALESCE(match_count, 12), 1), 24);
$$;

REVOKE ALL ON FUNCTION profession_jobs(text, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION profession_jobs(text, int) TO anon, authenticated;

-- =====================================================
-- 7. RPC profession_news — published news by cosine to profession
-- embedding, published professions only. Mirrors niche_news column
-- types exactly.
-- =====================================================

CREATE OR REPLACE FUNCTION profession_news(
  profession_slug text,
  match_count int DEFAULT 6
)
RETURNS TABLE (
  id uuid,
  slug text,
  title text,
  subtitle text,
  cover_image text,
  category text,
  published_at timestamptz,
  author text,
  read_time text
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT n.id, n.slug, n.title, n.subtitle, n.cover_image, n.category, n.published_at, n.author, n.read_time
  FROM news n
  JOIN professions p ON p.slug = profession_slug
  WHERE p.status = 'published'
    AND p.embedding IS NOT NULL
    AND n.embedding IS NOT NULL
    AND (n.status = 'published' OR n.status IS NULL)
    AND n.published_at >= now() - interval '90 days'
  ORDER BY n.embedding <=> p.embedding
  LIMIT LEAST(GREATEST(COALESCE(match_count, 6), 1), 24);
$$;

REVOKE ALL ON FUNCTION profession_news(text, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION profession_news(text, int) TO anon, authenticated;

-- =====================================================
-- 8. RPC quiz_professions — published professions for the quiz flow,
-- ordered by cluster then name (frontend lists clusters, then the
-- professions within each).
-- =====================================================

CREATE OR REPLACE FUNCTION quiz_professions()
RETURNS TABLE (
  slug text,
  name text,
  cluster text
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p.slug, p.name, p.cluster
  FROM professions p
  WHERE p.status = 'published'
  ORDER BY p.cluster, p.name;
$$;

REVOKE ALL ON FUNCTION quiz_professions() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION quiz_professions() TO anon, authenticated;

-- =====================================================
-- Harden search_path on functions created in 010 (pg_temp must resolve last)
-- =====================================================
ALTER FUNCTION niche_news(text, int) SET search_path = public, pg_temp;
ALTER FUNCTION niche_jobs(text, int) SET search_path = public, pg_temp;
